DFRobot_VL53L0X Library for Arduino
---------------------------------------------------------

This library provides the VL53L0X laser rangefinder API function

### Ready to start 
 
    void begin(uint8_t i2c_addr);
	i2c_addr:Set I2C sub-device address
    
### Send data to I2C device
   
    void writeData(unsigned char Reg ,unsigned char *buf, unsigned char Num);

### Read data from I2C device
    
	void readData(unsigned char Reg, unsigned char Num);

### 设置i2c设备地址
   
    void setDeviceAddress(uint8_t newAddr);
	
### The function validates high-precision measurement
   
    void highPrecisionEnable(uint8_t NewState);
	ENABLE: 0.25mm precision
	DISABLE: 1mm precision
		
### Initialize data
   
    void DataInit();

### Read measurement results of the sensor
   
    void readVL53L0X();

### Set operational mode to VL53L0X
   
    void setMode(uint8_t mode, uint8_t precision);
	mode：Work mode settings
		Single：Single mode  
		Continuous：Back-to-back mode
	precision：Set measurement precision
		High：High precision(0.25mm)
		Low: Low precision(1mm)
	
### Start measuring distance
   
    void start();

### Stop measurement
	
	void stop();
	
### get distance data
	
	uint16_t getDistance();
		
### get ambient count
		
	uint16_t getAmbientCount();
		
### get signal count

	uint16_t getSignalCount();
		
### get Status flag
		
	uint8_t getStatus();
	

 * @file DFRobot_VL53L0X.h
 * @brief DFRobot's Laser rangefinder library
 * @n This example provides the VL53L0X laser rangefinder API function

 * @copyright	[DFRobot](http://www.dfrobot.com), 2016
 * @copyright	GNU Lesser General Public License
 
 * @author [LiXin]
 * @version  V1.0
 * @date  2017-8-21
 * @https://github.com/DFRobot/DFRobot_VL53L0X